### ISSUE TITLE
More handy options to buy

### ISSUE THREAD

**Issue by Darth-Coin** [cointastical/Physical-Locations-Bitcoin#1]
You can add also telegram bots
https://t.me/lnp2pBot - Telegram bot buy/sell P2P through LN (mostly LATAM but also in EU/US)
https://t.me/BitcoinVoucherBot - Azte.co Telegram Bot buy BTC on LN

Mobile broker apps (only buy BTC)
https://swanbitcoin.com - simple, KYC
https://amber.app - LN, DCA, only US/AUS
https://xsats.com/ - (only UK) simple, KYC, LN supported
https://pocketbitcoin.com/ - buy BTC with LN, non-custodial
https://relai.ch - simple no-KYC (Swiss bank)
https://bitkipi.com/ - easy to buy and 100% control your wallets, even connect with own node
https://pocketbitcoin.com/ - support LN, non-custodial
https://ramp.network - simple no-KYC
https://www.luno.com/ - KYC, simple mobile app
https://river.com/ - only US now
https://lastbit.io/ - simple, LN supported, also VISA card

**Comment by cointastical** [comment]
Ok, I've updated the content to include an a Buy Online section.
A few things:
- Amber app, does not have LN
- xSats has suspended operations, working on a release with compliance to new regs   
- Lastbit (closed beta) is launching Striga (with an "early access" invite)
